# Generated by Django 3.2.9 on 2021-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='car',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
